### ISSUE TITLE
Docs: Is value key optional?

### ISSUE THREAD

**Issue by Eben60** [ModiaSim/SignalTables.jl#8]
On running the code from the very first example in the docs I get an 
`ERROR: KeyError: key :value not found`
Removing the line
`"attributes"    => Par(info  = "This is a test signal table")`
or changing it to 
` "attributes"    => Par(value = nothing, info  = "This is a test signal table"),`
fixes the error.

**Comment by MartinOtter** [comment]
Sorry, the latest documentation was not pushed. This is now fixed.
